### ISSUE TITLE
这个本地版本就跑不起来，我嫌费劲，直接用中文留言了。

### ISSUE THREAD

**Issue by vovasoft** [kumahq/kuma-counter-demo#57]
### What happened?

第一个问题，创建token文件需要增加日期参数，否则会直接报错，建议修改一下readme：--valid-for=24h

第二个问题，就是第二次启动kuma-dp run的时候，会提示9902端口被占用，这个问题我之前提过，有个老师说用export增加环境变量，我试了，好像不行，依然会报错。我建议开发者自己试一下。

新手教程很重要，尤其是非k8s环境，大部分人没有条件搭建k8s环境，其实用docker也行，但你们并没有docker教程。

第三个问题，我今天尝试用不同服务器运行kuma和其他服务，最新版的二进制文件，对gclib的版本要求很高，需要有2.28，2.29，并不方便，这非常不利于kuma的使用和宣传，你们知道升级C++相关的东西有多麻烦吗？

第四个问题，权限很复杂，在多服务器运行的时候提示cert.pem文件配置，例如你们会提示：kumactl generate tls-certificate --type=server --cp-hostname=，但这个脚本根本就无法运行，因为没有--cp-hostname这个参数，只有--hostname，建议你们更新一下。而且，即便是生成了pem文件，这个文件只支持内网IP，例如阿里云，外网地址依然无法访问。而且而且，即便在内网运行，依然会有各种错误。

已经3天了，我根本无法运行一个简单的Demo，相比其他service mesh框架，例如consul，20分钟就能完成demo的创建，而kuma用了3天无法完成1个简单的测试。

**Comment by jijiechen** [comment]
Duplication of https://github.com/kumahq/kuma-website/issues/2010
